version: '3'
services:
  postgres:
    container_name: 'attendance-system-postgres-database'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5434:5432'